meta_product_name: "Tripper"
meta_title: "Tripper | Match your trip"
meta_description: "For unique journeys full of surprises, think Tripper, the ultimate intelligent travel planning companion"
meta_image: "tripper_logo.png" # should exist in `app/assets/images/`
